### ISSUE TITLE
Non-existing covers linked for new movies

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#100]
When new movies (i.e. no imdb/trakt/tmdb info in database) are being processed after binary retrieval it looks them up and they get shown in the covers wall however for newer ones I've seen so far is that they have a linked cover in the database but they don't exist on the filesystem (failed to download?) so you get an error and no cover shown.

Few movies I noticed it with today:

tt1368153
tt0271196

In Admin-Edit site under 3rd Party API Keys I've added all the necessary api keys except those for giant bomb and anidb, since it happens only with new movies this one is a bit hard to recreate as I have to wait for something new to get post processed first.

Checked write permissions in case it was that but they are all setup per the docs (777 for resources etc..), all other things like previews / samples / xxx covers / nzbs are getting created but only for new movies covers it doesn't.

 Any ideas where this could be coming from?

// EDIT

Looked in the resources\covers\movies folder and seems some are getting created with an tt prefix, for example:

tt1368153-cover.jpg

So they exist just not with the default naming scheme for movie covers.

**Comment by DariusIII** [comment]
run misc/testing/PostProc/getTraktCovers.php to fix those.

**Comment by RickDB** [comment]
Don't have that one in <site root>misc/testing/PostProc/.

**Comment by DariusIII** [comment]
getTrakt.php, sorry.

**Comment by RickDB** [comment]
No problem and have it running now but probably gonna take a while to complete (30,830 movies), thanks for the help :+1:

**Comment by DariusIII** [comment]
Pushed the fix to dev.

**Comment by RickDB** [comment]
Happened with another movie today (tt0419058) however this time it didn't create the cover file as well so it links to a non-existing cover.
getTrakt.php script completed successfully and applied the fix before running it again just in case.

**Comment by RickDB** [comment]
Had it again with a completely new movie (2118624), linked cover to "<site>/covers/movies/2118624-cover.jpg" however file is nowhere to be found.

**Comment by DariusIII** [comment]
That is not a problem with your install, it is a bug in newznab-tmux, which i cannot hunt down. Sometimes i notice that the cover is there and after couple of seconds it is deleted.

**Comment by DariusIII** [comment]
Is this still happening?

**Comment by RickDB** [comment]
Haven't been able to test it with the latest DEV branch yet due to the amount of changes in it  but plan to do that this weekend if it doesn't have any breaking issues, will let you know how it goes.

**Comment by RickDB** [comment]
Not seeing any cover issues after running it for a day or so, looks like it's solved :+1:

**Comment by RickDB** [comment]
Had it again for the movie Soft Lad (2015), seems very rare now though.
