### ISSUE TITLE
Login - logged out after x minutes even with Remember me option ticked

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#101]
Just did some testing with a few users and even though the option "Remember me" option in the login window was ticked they are logged out eventually ( < 120 minutes estimate), database / web server never restarted so can't figure out why that is happening.
With NN+ this worked as I could stay logged in for weeks so don't think it's an php config issue at least, it must something like the "remember me" function not working or it's clearing the sessions.

Also noticed that the redirect URL you get when you have to re-log (redirectUrl=*) isn't redirecting to that url afterwards.

**Comment by DariusIII** [comment]
Which template? And yes, sometimes it happens, but after couple of logins you will stay logged in forever.

**Comment by RickDB** [comment]
Can re-create it with Omicron for one user and Omega (Omicron fork) for myself.
Re-logged a couple of times in the last few days but all users keep getting that prompt after a while.

**Comment by RickDB** [comment]
Found that in the cookie setter:

https://github.com/DariusIII/newznab-tmux/blob/master/newznab/controllers/Users.php#L640-641

It has an (time() + 2592000), is that the cookie expiry or am I misreading that?

**Comment by slug1982** [comment]
iirc I had the same issue when I moved from newznab. I had to remove the cookies in chrome for the domain.

**Comment by RickDB** [comment]
@slug1982 Thanks will try that, noticed I had 2 additional cookies leftover from the old site.

**Comment by RickDB** [comment]
For the other issue with redirect not working afer re-log I found that it was missing an hidden form attribute (redirect) in the login.tpl, fixed it in Omega theme like this:

https://github.com/RickDB/newznab-tmux-theme-omega/commit/2ec70d21874d91a6edf38a24759aac43c714fc51

**Comment by DariusIII** [comment]
Fixed the redirect, thanks for pointing me to it.

**Comment by RickDB** [comment]
Clearing the cookies indeed fixed it :+1: 

Did a quick comparison of the old and new cookies and for NN+ it was domain = "<domain name>"  cookies however for NN-TMUX it's all host= "<domain name>" so that looks like the reason it isn't overwriting the old cookies as besides that they were identical.

**Comment by DariusIII** [comment]
Closing this, as it is fixed.
