### ISSUE TITLE
Filtering out invalid releases by size/group size before they are indexed by Sphinx

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#102]
During the Update_releases process all releases are put in the releases table and visible with Sphinx searches right away, the remove by min/max group/category size is only ran every x number of runs so those will remain visible for a certain period depending on how fast update_releases runs.

So during that there are fake releases visible on the index which get retrieved by API / RSS / Search requests which I noticed with Couch and RSS readers.
Is it possible to let update_releases run the remove by min/max group/category size more often or maybe prevent those from being inserted into the Sphinx index?

For now I've modified the RSS / API / Search pages to a minimal 20MB release size which works well enough but of course not a good fix.

**Comment by DariusIII** [comment]
Will have a look at it.

**Comment by RickDB** [comment]
Thanks :+1: 

Btw in the last few days made a bunch of fixes which you can cherry pick if you want of course, no need to credit just happy to help.

https://github.com/DariusIII/newznab-tmux/commits/dev <-- some site specific but also common fixes

also made 2 new themes which can be added via git submodules:

https://github.com/RickDB/newznab-tmux-theme-omega/commits/master<-- based on Omicron but contains a few improvements here and there (trailer support / bugfixes) however is a work in progress.

https://github.com/RickDB/newznab-tmux-theme-gamma <-- theme based on my old nn+ one, modified it so that's compatible with nn-tmux, completely working and my main theme.
