### ISSUE TITLE
samples and previews not saving

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#103]
Just done a clean install from dev and its not saving anything into the covers area.

mediainfo and other things being generated okay so assuming the deep inspection all okay. Looked at post processing and "j" and "s" are popping up all okay.

Have the covers alias in the apache file and folder resources/* been set to 777.

Any ideas?

Cheers

**Comment by DariusIII** [comment]
Check if the covers are actualy there in the covers folders.

**Comment by bert0901** [comment]
Nothing at all, that's what I don't understand.

**Comment by bert0901** [comment]
Done some testing, and its trying to write to 

var/www/newznab/www/coverssample for example.

So not in the resources folder at all and also missing the "/"

Any ideas?

**Comment by bert0901** [comment]
Solved it

Add this to the constants file

// Refers to the covers folder
define('NN_COVERS', NN_RES . 'covers' .DS);

Cheers

**Comment by DariusIII** [comment]
That is in the file long time ago:

https://github.com/DariusIII/newznab-tmux/blob/master/www/automated.config.php#L41

**Comment by bert0901** [comment]
Its not in the dev branch in the constants file, the autiomated.config file is not in the dev branch.

**Comment by slug1982** [comment]
Is irc scrapper working for you bert?

**Comment by bert0901** [comment]
Yep, all working fine, I am using a znc server.

**Comment by DariusIII** [comment]
I am closing this. If needed reopne the issue.
