### ISSUE TITLE
populate_rt_indexes.php missing SphinxSearch reference

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#105]
The populate_rt_indexes.php script is missing a required reference to the SphinxSearch class, below is the modified file which has the reference at the top which allowed me to populate the indexes (failed before):

<www_root>\misc\sphinx\ populate_rt_indexes.php
https://gist.github.com/RickDB/f608a46b3c7984f0da29

**Comment by DariusIII** [comment]
Yeah, i missed it when switching class folders. Thanks.
