### ISSUE TITLE
Release files search with Sphinx

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#107]
nZEDb added release files to the Sphinx search some time ago which allowed searching thru file names, seems nn-tmux has some files modified for it (rt optimize script mentions it) however the populate_rt_indexes.php script only allows the releases tables at the moment.

Are there any plans to fork this over from nZEDb?

**Comment by DariusIII** [comment]
Same is added to newznab-tmux as it is added to nZEDb.

**Comment by RickDB** [comment]
Ah ok, saw this in the changelog some time ago which mentioned search by filenames:

2015-08-26 bart39
	Mrg: PR 1843, by ruhllatio - Sphinx Full-Text Search for Filenames.

However there's only search by release name at the moment and not filenames at least in the populate script, in optimized.php it does mention a releases_files_rt which doesn't exist (yet?):

https://github.com/nZEDb/nZEDb/blob/master/misc/sphinxsearch/optimize.php

**Comment by DariusIII** [comment]
I have added missing things to SphinxSearch class, you can try it.

**Comment by RickDB** [comment]
Tried it with a few wildcard searches of their filenames but doesn't seem to get any results, this is with a newly populated sphinx index (after the changes in dev).

**Comment by DariusIII** [comment]
I tried searching on nZEDb, did not find releases by their filenames either

**Comment by DariusIII** [comment]
This is potentially fixed in commit 21b644e7905c993b9cf4dbc7dfd6359aac216c05
