### ISSUE TITLE
RemoveCrapReleases not working

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#108]
When Sphinx is enabled and RemoveCrapReleases is run it will no longer remove files matching the "executable" option (not sure if affects more) from categories like movies / tv (returns 0 results)
However when I revert to the default search engine (NN_RELEASE_SEARCH_TYPE' = 0) it will return plenty of matches but so much more that I'm not sure if that is correct either (6000 in last 12hrs seems excessive).

This is with releases that have 1 file which have an .exe extension and are posted in a.b.multimedia with category Movies -> SD.

**Comment by DariusIII** [comment]
I have just updated SphinxSearch and related scripts, check if it is working now.

**Comment by RickDB** [comment]
Thanks, will re-populate indexes and test.

**Comment by RickDB** [comment]
Just tested with a few new releases but with Sphinx enabled it doesn't find and remove them.

**Comment by DariusIII** [comment]
Can you point me to a specific release?

**Comment by DariusIII** [comment]
Still waiting.....

**Comment by RickDB** [comment]
Sent it via IRC some time ago but it's with all movie / xxx releases that are below < 100MB.

**Comment by DariusIII** [comment]
I have pushed one change to ReleaseRemover that should deal with the problem.

**Comment by RickDB** [comment]
Thanks, will test it out today and let you know how it goes.

**Comment by RickDB** [comment]
Tried it and doesn't remove the fake .exe releases like:

Searchname: Sinister 2 2015 720p WEBRiP x264 AC3-RiPRG
Filename: Sinister_2_2015_720p_WEBRiP_x264_AC3-RiPRG 10_12_2015.exe
Poster: support@razor.com (Razor1911)
Posted: Dec 6, 2015 ( Today )

**Comment by DariusIII** [comment]
Why don't you just block the damn poster?

**Comment by RickDB** [comment]
Because you can't block posters based on categories or other variables (like size) when using the blacklist regexp option, it works when changing ReleaseRemover.php to not use the sphinx option which is fine but slower of course.

**Comment by DariusIII** [comment]
this particular release has support@razor.com as poster, which is obviously always used to post fake releases.

**Comment by RickDB** [comment]
For that one it should work just don't like the idea of poster blacklists in general as you run the risk of removing good releases, better to remove them based on certain criteria so even when they change the poster name it will stay working and have a bit more control over it at the same time.
The current workaround is fine though just slower, removed the SPHINX case here:

https://github.com/DariusIII/newznab-tmux/blob/dev/newznab/ReleaseRemover.php#L428

**Comment by DariusIII** [comment]
Fixed in commit 21b644e7905c993b9cf4dbc7dfd6359aac216c05
