### ISSUE TITLE
reqid releases not being created.

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#112]
Just done a new install with dev and the new schema file.

No releases are being created with reqid in their names.

Downloaded 1,000,000 headers. They are in the binaries table okay.

But nothing in releases.

Any ideas?

Cheers

Thanks for sorting out TV stuff.

**Comment by DariusIII** [comment]
It should be working, there was a PR fixing it.

**Comment by bert0901** [comment]
Any ideas what the PR was?

many Thanks

**Comment by DariusIII** [comment]
https://github.com/DariusIII/newznab-tmux/commit/035e2e5d19c6bbb757f20fff13bfc92445582e34

**Comment by bert0901** [comment]
Cheers many thanks for that. Changed back and all working fine now.
