### ISSUE TITLE
match_prefiles.php finding lots

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#113]
When I run this file, its finding lots that aren't being picked up in general processing.

Anyway this can be incorporated into the post processing?

Many Thanks

**Comment by DariusIII** [comment]
I will add it in some form to tmux.

**Comment by bert0901** [comment]
I have replaced my nzbimport to use those fields as don't use that, and used the numerical value from there.

Was thinking of adding this to decrypt section instead at some point. But then it would mean messing around with tmux edit screen and adding specific values.

Many Thanks

**Comment by bert0901** [comment]
There are a few scripts that could be run at specific times that not used all the time. Like the check covers and this one.

By having fields in the tmux edit where can add certain php file names to run at a specific time.

Like the monitor section, say 4-5 fields where can add specific names of files to run.

Just an idea.

**Comment by DariusIII** [comment]
This script requires too much resources to be used in loops. Best is to run it manually (i mean the match_prefiles).

**Comment by bert0901** [comment]
Many Thanks for response
