### ISSUE TITLE
a few things.

### ISSUE THREAD

**Issue by shempe** [DariusIII/newznab-tmux#114]
every then a fresh install.
latest dev

No import from:
resources/db/schema/nntmux_fi_schema.sql
Bug:
  PARTITION books VALUES LESS THAN (8000);
  );
must be:
  PARTITION books VALUES LESS THAN (8000)
  );

a few bugs from the log

Newznab\db\DB.queryDirect] [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newznab.binaries_29' doesn't exist]

This one is a little nasty...
newznab\db\DB.queryInsert] [SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'unmatched parentheses at offset 21' from regexp]
[newznab\db\DB.queryInsert] [INSERT INTO releases (name, searchname, totalpart, groupid, adddate, guid, categoryid, regexid, postdate, fromname, size,
reqid, passwordstatus, completion, haspreview, nfostatus, nzbstatus, isrenamed, iscategorized, reqidstatus, preid) VALUES ('b5fda91a7a932-M2M3NmViOWI3OWQwNzc2YjlmNDhjZDYx', 'b5fda91a7a932-M2M3NmViOWI3OWQwNzc2YjlmNDhjZDYx', 12, 19, now()
, 'e3961c46d3f3b20535c97e9fb30f3dc8782812c5', 10, 1832, '2016-02-18 14:25:17', 'JBinUp.com <JBinUp@JBinUp.local>', 0, null , -1, 100,-1, -1, 0, 0, 1, 0, 0)]

looks like a problem with the trigger. 
I think its is not a good to use double space´s in the trigger.

newznab\db\DB.queryDirect] [SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.prehashid' in 'where clause']
[newznab\db\DB.queryDirect] [SELECT r.id AS releaseid, r.guid, r.groupid FROM releases r WHERE r.guid LIKE 'a%' AND r.nzbstatus = 1 AND r.proc_par2 = 0 AND r.prehashid = 0 ORDER BY r.postdate ASC LIMIT 2]

maybe i made something wrong but.
resources/db/schema/nntmux_fi_schema.sql
had no prehashid

**Comment by shempe** [comment]
The code for fetching the Group updates looks not very stable, It get stuck very often.
It was running over night get stuck after half hour. and then not running at all.
Is there a timeout for this?

I see many:
[newznab\NNTP.dataError] [Code 205: Unexpected response: 'Goodbye' Skipping group:...
205 sounds like a normal close to me so.
Maybe a Problem with my Provider.

**Comment by shempe** [comment]
This is also New.

PHP Warning:  PDO::query(): Error reading result set's header in /var/www/html/newznab/newznab/db/DB.php on line 778
 PHP Warning:  PDO::query(): MySQL server has gone away in /var/www/html/newznab/newznab/db/DB.php on line 778

I have a old version running parallel to the same DB server with same provider 
and not one of this happens.

**Comment by DariusIII** [comment]
I must take another look, as, for start, there is no prehashid anymore. Which code for group updates?

**Comment by shempe** [comment]
For you Info I use a fresh install. New database, New code.
prehashid is still used in some code from what i see.

Look in you newznab-tmux/resources/db/schema/nntmux_fi_schema.sql
The trigger there have double spaces like here. This can cause trouble.
NEW.ishashed  =  1;

CREATE TRIGGER check_insert BEFORE INSERT ON releases FOR EACH ROW BEGIN IF NEW.searchname REGEXP '[a-fA-F0-9]{32}' OR NEW.name REGEXP '[a-fA-F0-9]{32}' THEN SET NEW.ishashed  =  1;ELSEIF NEW.name REGEXP '^\[ ?([[:digit:]]{4,6}) ?\]|^REQs*([[:digit:]]{4,6})|^([[:digit:]]{4,6})-[[:digit:]]{1}\[' THEN SET NEW.isrequestid  =  1; END IF; END $$


The part that get stuck is:
time,13707 nice -n19 php /var/www/html/newznab/misc/update/nix/multiprocessing/safe.php binaries
and its childs

It would be great to have a timeout here so if the process stucks it get killed.

**Comment by DariusIII** [comment]
I have pushed a fix for those prehashid caused errors.

**Comment by shempe** [comment]
I will test it.

**Comment by shempe** [comment]
Ok looks good. 
Nothing in the debug logs after I delete prehashid from releases.

**Comment by shempe** [comment]
do you use now userexccat or userexcat its a little mixed in the code

**Comment by DariusIII** [comment]
I have fixed the wrong tablename used in Users.php, themes do use $userexccat

**Comment by DariusIII** [comment]
I will close this. Please, for future reference, open separate issues so i can track them, do not group issues in one topic. Thank you.
