### ISSUE TITLE
Few Fixes maybe

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#117]
You may want to change these files in dev branch.

Going through regexless as never used before and want to give it a try.

newznab/NameFixer.php

829      - 					"INNER JOIN releasesearch rs ON rs.releaseid = r.id
829  + 					"INNER JOIN release_search_data rs ON rs.releaseid = r.id 
 
1008      - 						FROM predb p INNER JOIN predbhash h ON h.pre_id = p.id
1008  + 						FROM predb p INNER JOIN predb_hashes h ON h.pre_id = p.id 

newznab/ReleaseSearch.php 

43      - 			$this->fullTextJoinString = 'INNER JOIN releasesearch rs on rs.releaseid = r.id';
43  + 			$this->fullTextJoinString = 'INNER JOIN release_search_data rs on rs.releaseid = r.id'; 

 www/pages/preinfo.php (predbhash to predb_hashes)

198      - 					sprintf('SELECT * FROM predb p INNER JOIN predbhash ph ON ph.pre_id = p.id WHERE MATCH(hashes) AGAINST (%s) %s %s %s LIMIT %d OFFSET %d',
    198  + 					sprintf('SELECT * FROM predb p INNER JOIN predb_hashes ph ON ph.pre_id = p.id WHERE MATCH(hashes) AGAINST (%s) %s %s %s LIMIT %d OFFSET %d', 

 
215      - 					sprintf('SELECT * FROM predb p INNER JOIN predbhash ph ON ph.pre_id = p.id WHERE MATCH(hashes) AGAINST (%s) %s %s %s LIMIT %d OFFSET %d',
    215  + 					sprintf('SELECT * FROM predb p INNER JOIN predb_hashes ph ON ph.pre_id = p.id WHERE MATCH(hashes) AGAINST (%s) %s %s %s LIMIT %d OFFSET %d', 

misc/sphinxsearch/toggle_search_type.php  has lots of reference to releasesearch to release_search_data

Many Thanks for updating and keeping nntmux fresh.

**Comment by DariusIII** [comment]
I did not check by hand, but did the renaming automaticaly. Will fix these.

**Comment by DariusIII** [comment]
Pushed the fixed scripts. 5134bdeec070421f40cb3807bf8ab1f0ec76ca80

**Comment by bert0901** [comment]
Many Thanks
