### ISSUE TITLE
Missing first page in browse

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#118]
Done the updates up to "Fix wrong path to postprocess...." in dev

On each browse page, I am missing the first page. So page 1 is actually page 2 or results.

Gone through all themes and same issue.

I think its to do with changes to releases.php, but cannot be 100% sure.

Any ideas?

Many Thanks

**Comment by DariusIII** [comment]
It is fixed now, pushed the fix an hour ago.

**Comment by bert0901** [comment]
Cheers, many thanks.
