### ISSUE TITLE
Requestid Issue

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#32]
Had a look and this is not being done on the update_releases part of the scripts. Neither the local or web parts.

I thought it was working but it was the post processing was doing a search of the prehash table and then changing the names.

Many Thanks

**Comment by DariusIII** [comment]
It does not work because nn+ regexes remove everything and leave only the reqid number in the release name.

**Comment by bert0901** [comment]
Will just leave it to access the prehash tables on post processing.

Many Thanks for response

**Comment by bert0901** [comment]
Been looking into this a little, sorry php is not my strong point, vb.net man.

But instead of looking for the REQID in the release name, couldn't we just pass the value already found in row reqID?

**Comment by DariusIII** [comment]
reqID is not always there, and the name is always posted properly, just the regexes strip everything except the reqid.

**Comment by bert0901** [comment]
Think resolved this issue.

requestIDweb.php, line 47

SELECT r.ID, r.name, r.searchname, g.name AS groupname, r.groupID, r.categoryID, r.reqID

added the reqID to search

Line 118
$this->_release['name'] = $release['reqID'];

Now the WEB lookup does a check and changes the tables.

I know its not pretty and no checks to see if the reqID>0  but it does work.

**Comment by bert0901** [comment]
Instead of messing any more with the code, I just changed the check update trigger on the releases table to

ELSEIF NEW.reqID IS NOT NULL THEN SET NEW.isrequestid = 1;END IF;

All seems to be okay.

You will know more than me if this messes with anything else further down the line.
