### ISSUE TITLE
Part repair table

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#33]
Tried 3 different providers and this is getting failed parts all the time and partrepair is growing.

Compared to both my original installation and nzedb and they are getting none.

I always seem to be bearer of bad news.

Many Thanks

**Comment by DariusIII** [comment]
You are a worthy bug reporter :)
The problem lies in the way i modified binaries and releases to be able to use them for table per group, and newznab was never meant to be threaded, so binaries.php and releases.php do not cope well with it.

**Comment by bert0901** [comment]
"Worthy bug reporter" is better than pain in the arse complainer which I could have been called.

Thanks for the response.

**Comment by DariusIII** [comment]
Btw, in nZEDb you can choose to do partrepair or not, in newznab partrepair is always enabled. I did add an option to disable part repair, but nZEDb and nn+ work differently in this matter.

**Comment by bert0901** [comment]
Just an update on this, seems to be the same headers that are not being inserted each time.

Just picked 4 groups, started a fresh 400,000 download.

And each time, each group had almost exactly the same headers in the partrepair table, give or take a few.

**Comment by bert0901** [comment]
Been doing some tests.

I have taken out the sprint part of the insert when parts being placed into database.

Doesn't seem to be causing any issues.

**Comment by DariusIII** [comment]
Interesting, can you provide the exact line?

**Comment by DariusIII** [comment]
Heh, tried the same thing and the errors are gone. I would never think that that kind of fix would work.

**Comment by bert0901** [comment]
Couldn't give exact line as been playing and line spaces and stuff in my binaries.php

Me neither, spent days on it. Finally compared to a working binaries.php from way back, and that had the same line. Thought give it a shot.

Not sure what will happen if partrepair is actually required, but will do some backfilling which should find some.

Didn't want to go over to the new regexless version as already use the "other" indexer in a vm for comparison. Don't want to loose the soul of newznab, which is the annoying but sometimes better regexs.

Apologise not using git to push /pull changes and stuff, but have zero idea how to use it as a novice so just finding faults and solutions as I go.
