### ISSUE TITLE
NFO

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#36]
The nfo is being processed but the releasenfoID is not being updated correctly.

Had a quick look but couldn't find anything obvious.

Many Thanks

Ammendment

Looks like its just on the page view that its not showing the link as a button.

When you view the release in more detail, that part is working okay.

**Comment by DariusIII** [comment]
No, newznab-tmux does not update releasnfoIDmanymore, it uses nfostatus instead.

**Comment by bert0901** [comment]
Thanks, Changed line 113 to
{if $result.nfostatus > 0}<a href="{$smarty.const.WWW_TOP}/nfo/{$result.guid}"

from

{if $result.nfoID > 0}<a href="{$smarty.const.WWW_TOP}/nfo/{$result.guid}"
