### ISSUE TITLE
viewseries

### ISSUE THREAD

**Issue by m0rse** [DariusIII/newznab-tmux#41]
seems to be and error:
maybe just mine..
when i am viewing viewseries example: url/series/38657

backchat with jack whitehall and his dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad / Backchat with Jack Whitehall and his Dad

is tvrage etc writing it every time it finds an episode

**Comment by DariusIII** [comment]
I have checked my test setup, and i do not see this kind of behaviour.
