### ISSUE TITLE
Import predb_import_daily_batch.php doing weird things.

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#42]
Tried running this script and was working okay about 2 weeks ago. (I think about that time scale)

Now when I do a import it is adding LOTS of groups in group table with date as the group name, and also the rows are all over the place in the prehash table.

Example

Title : 13.36.30'
Source : pred.complete.on.at.least.1.site_i.imgur.com.92Z6J  
Files list : N 'Moto3.2014.America.720p.HDTV.x264-W4F'

Weird one this.

The php file is up to date, and tried the one before you made the change, but same output.

Any Ideas?

**Comment by DariusIII** [comment]
I use that script almost daily, and i haven't seen any similar behaviour. Can you send me an screenshot of bothe the groups and prehash with this data?

**Comment by bert0901** [comment]
Just done a clean install. Same issue.

![groups](https://cloud.githubusercontent.com/assets/3268711/5859306/570d649e-a251-11e4-9be9-f659df28c872.jpg)
![prehash](https://cloud.githubusercontent.com/assets/3268711/5859308/5b121224-a251-11e4-9b87-06b91fa2db6f.jpg)

**Comment by bert0901** [comment]
Just an update on this issue, Think it could be due to the PHP version release update recently as I have run all the SQL code separately directly on the sql server and all running okay.

On line 199 in predb_import_daily_batch.php its this part of that line that is causing the issue :+1: 

FIELDS TERMINATED BY '\\t\\t' ENCLOSED BY \"'\" LINES TERMINATED BY '\\r\\n'

Mainly the single quote part for the enclosed by section.

Moved all the sql to a query directly on the server and all runs okay.

**Comment by kevinlekiller** [comment]
Possibly an upstream bug. See 586174b846851fbd956a0f3d5bf2a4514665c367

**Comment by DariusIII** [comment]
Very likely, did not have time to "fix" it.

**Comment by bert0901** [comment]
Thanks for the responses on this issue.

**Comment by DariusIII** [comment]
I have pushed the change into util.php in dev branch. Can you check if the behaviour is the same?

**Comment by bert0901** [comment]
This update has solved the NFO formatting issue.

Will update tomorrow once I have a new predb update.

Many Thanks

**Comment by bert0901** [comment]
Yep, that has resolved the issue.

Many Thanks for that.
