### ISSUE TITLE
Some files not being processed

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#43]
The files are being found but no processing is being done, mainly file contents which has a knock on effect later down the line.

New Version of Tmux
229190-7[01/58] - "229190-2.0" yEnc (1/100) YES
228983-11[001/117] - "228983-3.0" yEnc (1/50) NO
147004-0[001/114] - "147004-2.0" yEnc (1/50) YES

Older Version of Tmux
229190-7[01/58] - "229190-2.0" yEnc (1/100) YES
228983-11[001/117] - "228983-3.0" yEnc (1/50) YES
147004-0[001/114] - "147004-2.0" yEnc (1/50) YES

Same with nZEDb so could be linked.

They are mainly series files that have the same initial numbers but different e.g -11 in above example.

Many Thanks

**Comment by bert0901** [comment]
Looked into this more.

Having a lot of releases getting a value "passordstatus=-2".

When I search for the entries they show up, but in the normal browse they are not there.

What is this value?

Cheers

**Comment by DariusIII** [comment]
Values from -1 to -6 mean releases that are still processed by ProcessAdditional.

**Comment by bert0901** [comment]
I thought that too, but not doing them when passwordstatus= -2

Seems just to miss those, not sure why. They don't get a retry for some reason.

Had a look at postprocessadditional.php in the tmux/lib folder and all seems to be okay.

**Comment by DariusIII** [comment]
Is this still an issue?

**Comment by bert0901** [comment]
Yep, All I have been doing is running a SQL to reset passwordstatus to 0 if it has value of -2.

Its a weird one as it follows no pattern, sometimes it is due to no file contents, some files will go to -7 value.

Some of the files have with the -2 value have been processed fully but just have this value of -2 so not showing up on the website.

To be honest I gave up on this issue as was spending lots of time on it and getting nowhere.

I see you have made changes in DEV so will copy those over and see if still happening.

**Comment by DariusIII** [comment]
I will close this isse then. If the problem persists, reopen this issue.
