### ISSUE TITLE
few things

### ISSUE THREAD

**Issue by shempe** [DariusIII/newznab-tmux#44]
maybe interesting for you.

/lib/copy_this/www/lib/Musik.php Line 168
Works suboptimal because there is no settings table.

/lib/DB/patches/0052~gamesinfo.sql Line 9
works better with genre_id

**Comment by DariusIII** [comment]
Damn, thanks for the info. Will be fixed in dev.

**Comment by DariusIII** [comment]
Fixed.

**Comment by shempe** [comment]
Great !! 
also for the tvrage fix , brings my table from 26GB back to normal..

But this puzzles me a bit.
newznab-tmux/lib/copy_this/www/pages/api.php
Line 669  
$language = $settings->queryOneRow(sprintf('SELECT audiolanguage FROM audiodata WHERE releaseID = %d', $release['ID']));
Without the audio data table is this not working so good.

**Comment by DariusIII** [comment]
Good catch, fixed.

**Comment by shempe** [comment]
I missing function is on the loose :)

lib/ProcessAdditional.php 
Line 588 cli_set_process_title

**Comment by shempe** [comment]
Im on last dev version and i see adding this faults in my logs:

fileperms(): stat failed for /var/www/html/nnplus/nzbfiles/f/faca56eba2d471541dfb36680e732d2c21ee5376.nzb.gz in /var/www/html/nnplus/misc/update_scripts/nix_scripts/tmux/lib/nzbcontents.php on line 266
[03-Mar-2015 10:02:08 Europe/Berlin] PHP Warning:  fopen(/var/www/html/nnplus/nzbfiles/f/f3cb03dfe57b93e7f1017ff3de9f4d5a10200a2e.nzb.gz): failed to open stream: No such file or directory in /var/www/html/nnplus/www/lib/util.php on line 160
[03-Mar-2015 10:02:08 Europe/Berlin] PHP Warning:  fileperms(): stat failed for /var/www/html/nnplus/nzbfiles/f/f3cb03dfe57b93e7f1017ff3de9f4d5a10200a2e.nzb.gz in /var/www/html/nnplus/misc/update_scripts/nix_scripts/tmux/lib/nzbcontents.php on line 266
[03-Mar-2015 10:02:36 Europe/Berlin] PHP Warning:  fopen(/var/www/html/nnplus/nzbfiles/0/0a6454d4cc6de76aac26e0714b835072c0ace9d4.nzb.gz): failed to open stream: No such file or directory in /var/www/html/nnplus/www/lib/util.php on line 160
[03-Mar-2015 10:02:36 Europe/Berlin] PHP Warning:  fopen(/var/www/html/nnplus/nzbfiles/0/02c68c0401d28d78b3b4f88984c998b7ff57d363.nzb.gz): failed to open stream: No such file or directory in /var/www/html/nnplus/www/lib/util.php on line 160

looks for me there is a path issue.

**Comment by DariusIII** [comment]
Yeah, i am aware of the issue. It happens because the file is removed right before it is postprocessed. The file realy does not exist.

**Comment by shempe** [comment]
Great! 
will do, I fight in the moment with 
Uncaught exception 'ErrorException' with message 'Non-static method PEAR::isError() should not be called statically ins spotnab and other places :)

**Comment by DariusIII** [comment]
That error won't go away, whatever you do, and there is nothing anyone can fix.. I disabled those static error messages, because they were going on my nerve.

**Comment by shempe** [comment]
yeah i know ist broken long time.
but I get fatal error in php 5.6 had to fix it with  (is_a($summary, 'PEAR_Error'))

**Comment by DariusIII** [comment]
There is a reset_postrpocessing script in lib/testing/DB/ folder.

**Comment by shempe** [comment]
Thanks, found the Script  php reset_postprocessing.php all false = 1,2M to go...

The fixes from the night worked. 
but still :+1: 

 fileperms(): stat failed for /var/www/html/nnplus/nzbfiles/2/2b5a76e1a8bff9edb02b0e986871596e738f5209.nzb.gz in /var/www/html/nnplus/misc/update_scripts/nix_scripts/tmux/lib/nzbcontents.php on line 266

**Comment by m0rse** [comment]
Also can confirm i am getting Warning: NZB is empty or broken for GUID: 

after update to latest dev

**Comment by shempe** [comment]
Now it looks better.

 lib/copy_this/www/lib/releases.php
-					'guid'           => $this->pdo->escapeString($this->createGUID($cleanRelName)),
+					'guid'           => $this->pdo->escapeString($relguid),

was it.

**Comment by DariusIII** [comment]
Yeah, it was a mistake on my end, creating 2 guids for same release, one was created for release itself and other for nzb, hence the release could not be postprocessed.

**Comment by shempe** [comment]
Ahh, Ok, so not real equal, Happend, 
Means throw away the last 4 Day´s to get a clean database, and find a method to clean the nzbfiles dir of trash.

**Comment by DariusIII** [comment]
Are you on master? As i have fixed this yesterday on dev.

**Comment by shempe** [comment]
Im on latest dev. 

Question why: instance of \NNTP and not instance \Info ?

+		$this->nntp = ($options['NNTP'] instanceof \NNTP ? $options['NNTP'] : new \NNTP(['Echo' => $this->echooutput, 'Settings' => $this->pdo]));
+		$this->nfo = ($options['Info'] instanceof Info ? $options['Nfo'] : new \Info(['Echo' => $this->echooutput, 'Settings' => $this->pdo]));

**Comment by DariusIII** [comment]
What do you mean?

**Comment by shempe** [comment]
lib/nzbcontents.php Line 96

**Comment by DariusIII** [comment]
Ah, typo. I'll push the change.

**Comment by shempe** [comment]
:-) sometimes Notice logging is not so bad.

**Comment by DariusIII** [comment]
I do have that on, but sometimes others have errors/notices/warnings i do not.

**Comment by shempe** [comment]
Yep i know that , i modded the code a bit, there i must look every time if i make the fault or the update.

**Comment by DariusIII** [comment]
For fileperms error:

You can also install it by downloading the newest version (recommended, as some RAR files require version 5+): Go to http://www.rarlab.com/download.htm, look for the newest unrar version (currently RAR 5.10), right click it and copy the link. Replace the link below with the one you copied:

mkdir -p ~/new_unrar

cd ~/new_unrar

wget http://www.rarlab.com/rar/rarlinux-x64-5.1.0.tar.gz

tar -xzf rarlinux*.tar.gz

sudo mv /usr/bin/unrar /usr/bin/unrar4

sudo mv rar/unrar /usr/bin/unrar

sudo chmod 755 /usr/bin/unrar

cd ~/

rm -rf ~/new_unrar

After updating to latest, stopped getting those.
