### ISSUE TITLE
The NZBGet URL you entered is invalid!

### ISSUE THREAD

**Issue by Fossil01** [DariusIII/newznab-tmux#70]
Whatever I try to enter as NZBGet server/username/password I get this error:

The NZBGet URL you entered is invalid!

Whenever I enter some stuff manually in the DB and then load the page it doesnt populate the input fields.

**Comment by DariusIII** [comment]
Check if you are missing the setting from users table.

**Comment by bdegier** [comment]
I have three fields in the users table  for username password and nzbget url. They are populated for my user.

**Comment by Fossil01** [comment]
This was fixed with Darius over IRC. I was missing two fields for queue type and style (new to TMUX)

**Comment by DariusIII** [comment]
Closing it as it is reported as fixed.
