### ISSUE TITLE
Maybe an issue

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#93]
A while ago I was saying had many incompletes and thought it was highwind providers

After a few clean installs and testing various providers and settings, it only happens when using update_binaries and when its set to complete threaded in tmux.

When set to simple threaded so only one group per thread it all woks fine. So guessing its something to do with the way complete_threaded handles tpg and headers but that is as far as my knowledge will go.

Love the new themes by the way.

Cheers

**Comment by DariusIII** [comment]
I am looking at the problem, as it is looks like an issue both in dev/master and dev-regexless with tpg enabled.

**Comment by bert0901** [comment]
Cheers, did a backfill and that seems to work okay.

If I set the group to redo last 2,000,000 it seems to find all and put all in the right table as most of the threads are used for the same group.

So just looks like if multiple groups have headers being downloaded if that is any help.

**Comment by DariusIII** [comment]
Is this still an issue?

**Comment by bert0901** [comment]
To be honest, I haven't looked to see if anything changed in last few weeks due to updates here. Left it on Simple threaded.

Will take a look in next couple of days and let you know.

Many Thanks

**Comment by bert0901** [comment]
Just had chance to have a look at it, and yes still the issue there.

Cheers
