### ISSUE TITLE
release.php error

### ISSUE THREAD

**Issue by bert0901** [DariusIII/newznab-tmux#95]
Line 2257 in newznab/conreollers/releases.php needs to be changed as throwing up errors.

Should be 

LEFT OUTER JOIN release_comments rc ON rc.releaseid = r.id

Cheers

**Comment by DariusIII** [comment]
damn, missed that one.

**Comment by bert0901** [comment]
No worries, glad to be of some help instead of issues.

I also added to resetdb.php the fields after spotnabsources.

"partrepair", "binaries", "collections", "releases", "spotnabsources", "releasesearch", "xxxinfo", "bookinfo", "consoleinfo","gamesinfo"
