### ISSUE TITLE
Few things Part 1

### ISSUE THREAD

**Issue by shempe** [DariusIII/newznab-tmux#97]
Hi there,
I found the time to make a fresh install of the latest dev.
Great work by the way.

First thing I noticed:

PHP Fatal error:  Call to undefined method Nfo::deleteReleaseNfo() in /var/www/html/newznab/newznab/controllers/Releases.php on line 2220

PHP Fatal error:  Call to undefined method TvRage::refreshRageInfo() in /var/www/html/newznab/www/admin/rage-edit.php on line 15

**Comment by shempe** [comment]
next thing I notice.

If i define an release category for an Regex it doesn't move the releases in that category

**Comment by DariusIII** [comment]
Interesting, as i have fixed the first error last week in push 934abe08a4abd4d0a72bc960811517e2ce11aa28.
For the second problem, i need more info.

**Comment by DariusIII** [comment]
I have fund the problem. Will fix ASAP.

**Comment by shempe** [comment]
Nah no need for ASAP,

Ok info for second Problem:

I define a new Category in Books "German" 7071
Ok i add a.b.ebook.german made a few Regexes and set the Category from the Regex to Books > German.

Normal every catch from that Regex should go to this Category and i don't need to mess with the Category.php and other stuff.

**Comment by DariusIII** [comment]
Can you paste the regex, or do a screenshot? I have pushed a fix to dev for your first problem.

**Comment by DariusIII** [comment]
Pushed a fix for your secobd, tvrage, problem.

**Comment by shempe** [comment]
![bildschirmfoto 2015-09-16 um 11 07 42](https://cloud.githubusercontent.com/assets/3007387/9900763/3b7826de-5c63-11e5-96a4-c05ac74f8c49.png)
![bildschirmfoto 2015-09-16 um 11 07 22](https://cloud.githubusercontent.com/assets/3007387/9900764/3b786b9e-5c63-11e5-827e-3f7f5e19e5ab.png)

**Comment by DariusIII** [comment]
Can you pastebin the regex and full release name?

**Comment by shempe** [comment]
Darn Ok i thought that has the first prio

**Comment by shempe** [comment]
Still the fatal error, looks like this deleteReleaseNfo($rel['id']); is not there typing error ?

**Comment by DariusIII** [comment]
What do you do to trigger this error?

**Comment by shempe** [comment]
Nothing special , tmux ist running and working.

**Comment by DariusIII** [comment]
Found the issue. WIll be fixed in next hour or so.

**Comment by shempe** [comment]
Thanks a lot , but no need to hurry. 

But would be nice to find a solution for the Regex problem this bugs me a lot.

**Comment by DariusIII** [comment]
Pastebin the regex, and full release name.

**Comment by shempe** [comment]
The fix does the job, perfekt.

Pastebin: http://pastebin.com/gwb8mEJu

**Comment by DariusIII** [comment]
Have you just added the category to Category.php?

**Comment by shempe** [comment]
I inserted in the category table mysql.
If you insert it in the Category.php you are not so flexible because you need fixed checks.
You can write your regx to, maybe catch all german tv or french movie and put it in the right category´s.
In the past it was working so.

**Comment by DariusIII** [comment]
Check if any error is thrown.

**Comment by shempe** [comment]
I don't find a error, but found out it is used in
/www/lib/releaseregex.php as categoryID
I think there it losses its functionality

**Comment by shempe** [comment]
In Progress don't go to 0 is this new ?

![bildschirmfoto 2015-09-17 um 13 03 29](https://cloud.githubusercontent.com/assets/3007387/9931552/e2bee6ec-5d3c-11e5-963e-69fc05b65905.png)

**Comment by shempe** [comment]
big update whow...

I switched today to latest dev.. 

Latest Dev 306950e

newznab/newznab/libraries/Forking.php
newznab/newznab/processing/post/AniDB.php
add 
use newznab\NZB;

newznab/config/settungs.php
newznab/utility/Misc.php needs to be existent.

**Comment by shempe** [comment]
question? 
rename rageid in releases to tvinfoid or duplicate it ?

**Comment by DariusIII** [comment]
You can duplicate it safely. It will be replaced anyway in due time.

**Comment by shempe** [comment]
ok done .. 
add new col tvinfoid  int 11 null and then..
update releases SET tvinfoid = rageid

**Comment by shempe** [comment]
Checking the logs..

log from decrypt hashes get a:
Could not open input file: /var/www/html/newznab/misc/update_scripts/postprocess_pre.php
and he is right...

**Comment by shempe** [comment]
PHP Fatal error:  Class 'Genres' not found in /var/www/html/newznab/newznab/Console.php on line 552
maybe delete the \ in protected function _loadGenres()

**Comment by DariusIII** [comment]
Pushed the fix for both problems.

**Comment by shempe** [comment]
superb. 
im debugging in the moment the irc scraper because:
Base table or view not found: 1146 Table 'newznab.predb_hashes' doesn't exist
some leftovers from nzedb

**Comment by DariusIII** [comment]
Oh, damn it.

**Comment by shempe** [comment]
but the predb_hashes entry must be hidden somewhere, im a little puzzled in the moment

**Comment by shempe** [comment]
Ok found it , trigger from prehash was the problem pointing to prefab_hashes ..

**Comment by shempe** [comment]
predb_hashes

**Comment by shempe** [comment]
Latest dev:

Base table or view not found: 1146 Table 'newznab.release_search_data' doesn't exist
Maybe change in newznab\Namefixer.php and nawznab\ReleaseRemover.php
to releasesearch ?

**Comment by shempe** [comment]
Latest dev:

Fatal error: Call to undefined method newznab\NZB::NZBPath() in /var/www/html/newznab/newznab/processing/post/ProcessAdditional.php

because public function NZBPath is not in newznab\NZB

**Comment by DariusIII** [comment]
Pushed the fixes to dev. I am not running dev, so errors like this do happen.

**Comment by shempe** [comment]
No Problem for me.
 I´m running dev and report what I find. it, 
if its Ok for you ?

**Comment by DariusIII** [comment]
Sure, go ahead. This way i can fix problems i introduce.

**Comment by shempe** [comment]
Better use releasesearch not relesesearch

**Comment by DariusIII** [comment]
Pushed the fix.

**Comment by shempe** [comment]
Latest dev:

Fatal error: Class 'newznab\TraktTv' not found in /var/www/html/newznab/newznab/Movie.php on line 1094

**Comment by DariusIII** [comment]
Fixed and pushed.
